### ISSUE TITLE
Bioconda installation

### ISSUE THREAD

**Issue by Thexiyang** [Finesim97/MetaErgInstallHelper#1]
Thanks for providing a new way to install MetaErg. It may depend on system. I have tried many times to install using this MetaErgInstallHelper. It just does not work out. It will great if you can create bioconda / packages. So we can just install it using something like: conda install metagerg.  Is it possible?

**Comment by Finesim97** [comment]
Hi, this was my original intention, but the problem are programs like SignalP and TMHMM which don't allow redistribution via Conda. I noticed that sometimes there are problems with installation on some systems, but usually it is possible to use the installer (with small changes).  Today I worked with a colleague which tried to install it on a windows based network drive, where the unpacking of SignalP fails. Can you provide screenshots/logs of the installation process?  

I thought of creating a package just without SignalP and TMHMM, but those are the ones which require most of the modifications.

**Comment by Finesim97** [comment]
Just created a more elegant solution, will close the issue for now.

**Comment by Thexiyang** [comment]
Cool! Now I have successfully installed it using the new solution! Thanks a lot!
