### ISSUE TITLE
error: cannot write .cpanm

### ISSUE THREAD

**Issue by aimirza** [Finesim97/MetaErgInstallHelper#3]
I had an issue where when trying to run the script "bash installMetaErg.sh metaerginstall 2>&1 | tee metaErgInstallLog.txt" and error would pop up that says it cannot write the directory ".cpanm" in the home directory. When I created the directory in my home directory it finally worked.

**Comment by Finesim97** [comment]
Hi,
Thank you for reporting this. Will add a directory creation step. 

Be careful, metaerg currently has some issues. You might want to revert to an older version:
https://github.com/xiaoli-dong/metaerg/issues/5#issuecomment-559011398
Best wishes.

**Comment by aimirza** [comment]
Thanks. But I didnt have any issues with -d parameter when running the test. Perhaps because the database was installed in the MetaErgs default database directory
