### ISSUE TITLE
Can't locate Bio/SeqIO.pm in @INC

### ISSUE THREAD

**Issue by s4251484** [Finesim97/MetaErgInstallHelper#4]
hi @Finesim97 and team

thanks for creating this helper! my installation was successful, but having problem to run this Perl script. any idea?

(/RDS/Q1034/conda/metaerg) s4251484@tinaroo1:.../MetaErg/metaerg/bin> /RDS/Q2348/MetaErg/metaerg/bin/metaerg.pl
Can't locate Bio/SeqIO.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /RDS/Q2348/MetaErg/metaerg/bin/metaerg.pl line 10.
BEGIN failed--compilation aborted at /RDS/Q2348/MetaErg/metaerg/bin/metaerg.pl line 10.

**Comment by Finesim97** [comment]
Hi,
It seems like the wrong Perl (System installation, not Conda env) is being used. Metaerg uses the `/usr/bin/env` command to find it. I am a little bit confused by your paths:
`/RDS/Q1034/conda/metaerg`: This is the path called `metaerginstall` in the manual?
`/RDS/Q2348/MetaErg/metaerg`: Another metaerg installation path?

Could you try in a new session (new terminal/ssh connection):

``` sh
which perl
conda activate /RDS/Q1034/conda/metaerg
which perl
metaerg.pl
```
When giving no path, the version installed by the installed will be used. Do you have to use the version in `/RDS/Q2348/`? Does it contain the reference data, you want to use?

**Comment by s4251484** [comment]
> Hi,
> It seems like the wrong Perl (System installation, not Conda env) is being used. Metaerg uses the `/usr/bin/env` command to find it. I am a little bit confused by your paths:
> `/RDS/Q1034/conda/metaerg`: This is the path called `metaerginstall` in the manual?
> `/RDS/Q2348/MetaErg/metaerg`: Another metaerg installation path?
> 
> Could you try in a new session (new terminal/ssh connection):
> 
> ```shell
> which perl
> conda activate /RDS/Q1034/conda/metaerg
> which perl
> metaerg.pl
> ```
> 
> When giving no path, the version installed by the installed will be used. Do you have to use the version in `/RDS/Q2348/`? Does it contain the reference data, you want to use?

hi @Finesim97 thanks for your prompt reply!
below is what I got

which perl
/usr/bin/perl

module load anaconda (I ran this on a cluster, hence module loading)
source activate /RDS/Q1034/conda/metaerg
 
(/RDS/Q1034/conda/metaerg) s4251484@tinaroo2:~> which perl
/RDS/Q1034/conda/metaerg/bin/perl

yea I have my conda env in this path /RDS/Q1034/conda/metaerg
and /RDS/Q2348/MetaErg/metaerg (supposedly metaerginstall) is where I downloaded the gz files and your script.

**Comment by Finesim97** [comment]
Ok,
The script automatically creates a custom Conda environment (stored as `metaerginstall` according to the Readme), into which metaerg is downloaded and installed into. 

Did you create the conda env /RDS/Q1034/conda/metaerg with the script?  Did the command (`metaerg.pl`) without any path print anything?

**Comment by s4251484** [comment]
> Ok,
> The script automatically creates a custom Conda environment (stored as `metaerginstall` according to the Readme), into which metaerg is downloaded and installed into.
> 
> Did you create the conda env /RDS/Q1034/conda/metaerg with the script? Did the command (`metaerg.pl`) without any path print anything?

yea it is a fix! 
sorry I acted smart and created my own conda env! deleted it and activate the conda env which the script created and now my metaerg is working now! thanks!
